In [11]:
import numpy as np


x = np.zeros(64).reshape(8,8)
for i in range(8):
    if (i%2==0):
        for j in range(1,8,2):
            x[i,j] = 1
    if (i%2!=0):
        for j in range(0,8,2):
            x[i,j] = 1

print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [10]:
import numpy as np


x = np.arange(25).reshape(5,5)
for i in range(5):
    for j in range(5):
        x[i,j] = j

print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [9]:
import numpy as np


x = np.random.random((3,3,3))
print(x)

[[[0.34206426 0.71727858 0.07944077]
  [0.86669557 0.44264335 0.27194058]
  [0.62824418 0.61708558 0.42274494]]

 [[0.42056486 0.39503375 0.60087984]
  [0.83122035 0.67041768 0.15255067]
  [0.28180038 0.42167705 0.98209753]]

 [[0.12617935 0.94519182 0.80746239]
  [0.04572491 0.91492108 0.37524806]
  [0.02047463 0.34391263 0.91129965]]]


In [8]:
import numpy as np


n = int(289)
x = np.zeros(n).reshape(int(n**(1/2)),int(n**(1/2)))

for i in range(int(n**(1/2))):
    for j in range(int(n**(1/2))):
        if (i==0 or j==0 or i==int(n**(1/2))-1 or j==int(n**(1/2))-1):
            x[i,j] = 1
        else:
            x[i,j] = 0

print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [7]:
import numpy as np

x = np.array([np.random.random() for _ in range(10)])
print(np.sort(x)[::-1])

[8.67345532e-01 6.16372956e-01 6.11890976e-01 5.19708268e-01
 4.91131570e-01 2.80528353e-01 1.01611596e-01 4.29057013e-02
 1.28293854e-02 4.13064455e-04]


In [6]:
import numpy as np


x = np.array([1,2,3,4,5,6])
print(x.ndim, x.size, x.shape)

1 6 (6,)


In [5]:
import pandas as pd


x = pd.Series([2, 7])
y = pd.Series([6, 0])

print(((y[0]-x[0])**2+((y[1]-x[1])**2))**(1/2))

8.06225774829855


In [12]:
import pandas as pd


dtfr = pd.read_csv(r"C:\Users\Timur\OneDrive\Рабочий стол\study\sem3\ИИ\AI_MIREA\diabetes.csv")
dtfr.head(10)

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   
5   55   Male      Yes        Yes                 No      Yes        Yes   
6   57   Male      Yes        Yes                 No      Yes        Yes   
7   66   Male      Yes        Yes                Yes      Yes         No   
8   67   Male      Yes        Yes                 No      Yes        Yes   
9   70   Male       No        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   
5             No             Yes     Yes           No             Yes   
6            Yes              No      No           No             Yes   
7             No             Yes     Yes          Yes              No   
8            Yes              No     Yes          Yes              No   
9             No             Yes     Yes          Yes              No   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive  
5              No              Yes      Yes     Yes  Positive  
6             Yes               No       No      No  Positive  
7             Yes              Yes       No      No  Positive  
8             Yes              Yes       No     Yes  Positive  
9              No               No      Yes      No  Positive

In [13]:
import pandas as pd


dtfr = pd.read_csv(r"C:\Users\Timur\OneDrive\Рабочий стол\study\sem3\ИИ\AI_MIREA\diabetes.csv")

print(dtfr.head(5))
print(dtfr.tail(5))
print(dtfr.shape)
print(dtfr.describe())
print(dtfr.iloc[3:5])

   Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      

In [2]:
import pandas as pd
from sklearn import preprocessing as pr


dataframe = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")
scaler = pr.MinMaxScaler()
scaler2 = pr.StandardScaler()

dataframe[['sepal_length_cm']] = scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = scaler2.fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]