In [1]:
import numpy as np


x = np.zeros(64).reshape(8,8)
for i in range(8):
    if (i%2==0):
        for j in range(1,8,2):
            x[i,j] = 1
    if (i%2!=0):
        for j in range(0,8,2):
            x[i,j] = 1

print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [2]:
import numpy as np


x = np.arange(25).reshape(5,5)
for i in range(5):
    for j in range(5):
        x[i,j] = j

print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [3]:
import numpy as np


x = np.random.random((3,3,3))
print(x)

[[[0.24481471 0.24836873 0.85802352]
  [0.35403402 0.8032954  0.43583307]
  [0.2117176  0.75965733 0.6085336 ]]

 [[0.15449341 0.74768693 0.21130542]
  [0.24282724 0.2250304  0.0375716 ]
  [0.48347125 0.46439777 0.87265885]]

 [[0.85800509 0.19061202 0.56760814]
  [0.31862889 0.39646276 0.54396838]
  [0.39915283 0.06537872 0.14857877]]]


In [7]:
import numpy as np


n = int(289)
x = np.zeros(n).reshape(int(n**(1/2)),int(n**(1/2)))

for i in range(int(n**(1/2))):
    for j in range(int(n**(1/2))):
        if (i==0 or j==0 or i==int(n**(1/2))-1 or j==int(n**(1/2))-1):
            x[i,j] = 1
        else:
            x[i,j] = 0

print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [9]:
import numpy as np

x = np.array([np.random.random() for _ in range(10)])
print(np.sort(x)[::-1])

[0.91732608 0.85425195 0.79737143 0.71620137 0.55957118 0.52053386
 0.51400317 0.39780038 0.32882471 0.14662038]


In [10]:
import numpy as np


x = np.array([1,2,3,4,5,6])
print(x.ndim, x.size, x.shape)

1 6 (6,)


In [6]:
import pandas as pd


x = pd.Series([2, 7])
y = pd.Series([6, 0])

print(((y[0]-x[0])**2+((y[1]-x[1])**2))**(1/2))

8.06225774829855


In [3]:
import pandas as pd


dtfr = pd.read_csv("/home/lary_stef/Documents/australian.csv")
dtfr.head(10)

A1   A2   A3  A4  A5  A6   A7  A8  A9  A10  A11  A12  A13  A14  A15_class
0   1   65  168   2   4   4   39   0   0    1    1    2   32  161          0
1   0   72  123   2   8   4    5   0   0    1    0    2   53    1          0
2   0  142   52   1   4   4   31   0   0    1    1    2   98    1          0
3   0   60  169   1   5   3    1   1   1   12    1    2    1    1          1
4   1   44  134   2   6   4   46   1   1   15    0    2   18   68          1
5   0    4   20   2   8   8   37   1   1    3    0    2   32    1          1
6   1   16  119   2   3   4    4   0   0    1    0    2   18   50          0
7   0  330   94   2  11   8   66   1   1    7    0    2   12  120          1
8   1  126   33   1   2   8   65   0   0    1    0    2   61  117          0
9   0  315  125   2   4   8  100   1   1    4    1    2   32   36          0

In [7]:
import pandas as pd


dtfr = pd.read_csv("/home/lary_stef/Documents/australian.csv")

print(dtfr.head(5))
print(dtfr.tail(5))
print(dtfr.shape)
print(dtfr.describe())
print(dtfr.iloc[3:5])

   A1   A2   A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15_class
0   1   65  168   2   4   4  39   0   0    1    1    2   32  161          0
1   0   72  123   2   8   4   5   0   0    1    0    2   53    1          0
2   0  142   52   1   4   4  31   0   0    1    1    2   98    1          0
3   0   60  169   1   5   3   1   1   1   12    1    2    1    1          1
4   1   44  134   2   6   4  46   1   1   15    0    2   18   68          1
     A1   A2   A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15_class
685   1  163  160   2  14   4  99   1   0    1    0    2    1    1          1
686   1   49   14   2   8   4   4   0   0    1    0    2    1   35          0
687   0   32  145   2   6   4   3   1   0    1    0    2   32    1          1
688   0  122  193   2  14   8  67   1   1    2    0    2   38   12          1
689   1  245    2   2  10   4   2   0   1    2    0    1  159    1          1
(690, 15)
               A1          A2          A3          A4          A5 

In [11]:
import numpy as np
from sklearn import preprocessing as pr


dataframe = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")
scaler = pr.MinMaxScaler()
scaler2 = pr.StandardScaler()

dataframe[['sepal_length_cm']] = scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = scaler2.fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]