In [1]:
import numpy as np


x = np.zeros(64).reshape(8,8)
for i in range(8):
    if (i%2==0):
        for j in range(1,8,2):
            x[i,j] = 1
    if (i%2!=0):
        for j in range(0,8,2):
            x[i,j] = 1

print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [2]:
import numpy as np


x = np.arange(25).reshape(5,5)
for i in range(5):
    for j in range(5):
        x[i,j] = j

print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [3]:
import numpy as np


x = np.random.random((3,3,3))
print(x)

[[[0.24481471 0.24836873 0.85802352]
  [0.35403402 0.8032954  0.43583307]
  [0.2117176  0.75965733 0.6085336 ]]

 [[0.15449341 0.74768693 0.21130542]
  [0.24282724 0.2250304  0.0375716 ]
  [0.48347125 0.46439777 0.87265885]]

 [[0.85800509 0.19061202 0.56760814]
  [0.31862889 0.39646276 0.54396838]
  [0.39915283 0.06537872 0.14857877]]]


In [7]:
import numpy as np


n = int(289)
x = np.zeros(n).reshape(int(n**(1/2)),int(n**(1/2)))

for i in range(int(n**(1/2))):
    for j in range(int(n**(1/2))):
        if (i==0 or j==0 or i==int(n**(1/2))-1 or j==int(n**(1/2))-1):
            x[i,j] = 1
        else:
            x[i,j] = 0

print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [9]:
import numpy as np

x = np.array([np.random.random() for _ in range(10)])
print(np.sort(x)[::-1])

[0.91732608 0.85425195 0.79737143 0.71620137 0.55957118 0.52053386
 0.51400317 0.39780038 0.32882471 0.14662038]


In [10]:
import numpy as np


x = np.array([1,2,3,4,5,6])
print(x.ndim, x.size, x.shape)

1 6 (6,)
